version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/
  - source: style.css
    destination: /var/www/html/
  - source: image/
    destination: /var/www/html/image/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/remove_old_files.sh
      timeout: 300
      runas: root
    - location: scripts/debug_archive.sh
      timeout: 300
      runas: root
    - location: scripts/check_image_folder.sh  # New script to ensure the image folder exists
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
